FROM python:3.11-slim
WORKDIR /app

# Copy the specific test requirements file
COPY device/sf_watering/watering_app/server/tests/requirements-test.txt .

# Install the updated dependency list
RUN pip install --no-cache-dir -r requirements-test.txt

COPY . .

# Run the test suite
CMD ["pytest"]