name: SIM-FLOW Integration Tests

on:
  workflow_run:
    workflows: ["SIM-FLOW FW Build CI"]
    types:
      - completed

jobs:
  integration-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        idf_target: ["esp32", "esp32s3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create CI directories
        run: mkdir -p .ci/device_bin

      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: qemu-binary-${{ matrix.idf_target }}
          path: .ci/device_bin
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Compose Tests
        env:
          TARGET_CHIP: ${{ matrix.idf_target }}
        run: |
          # Note the updated path to the .ci folder
          docker-compose -f .ci/docker-compose.yml up --build \
            --abort-on-container-exit \
            --exit-code-from test-runner

      - name: Cleanup
        if: always()
        run: docker-compose -f .ci/docker-compose.yml down